[ci] Add check_error_codes to gh actions
ghstack-source-id: b6dbee275be58c14341dec1a823ff7773e5a6a59
Pull Request resolved: https://github.com/facebook/react/pull/30354

diff --git a/.github/workflows/runtime_build_and_test.yml b/.github/workflows/runtime_build_and_test.yml
--- a/.github/workflows/runtime_build_and_test.yml
+++ b/.github/workflows/runtime_build_and_test.yml
@@ -290,6 +290,36 @@ jobs:
             ./build.tgz
             ./build2.tgz
 
+  check_error_codes:
+    name: Search build artifacts for unminified errors
+    needs: build_and_lint
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 18.20.1
+          cache: yarn
+          cache-dependency-path: yarn.lock
+      - name: Restore cached node_modules
+        uses: actions/cache@v4
+        id: node_modules
+        with:
+          path: "**/node_modules"
+          key: ${{ runner.arch }}-${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
+      - run: yarn install --frozen-lockfile
+      - name: Restore archived build
+        uses: actions/download-artifact@v4
+        with:
+          path: build
+          merge-multiple: true
+      - name: Display structure of build
+        run: ls -R build
+      - name: Search build artifacts for unminified errors
+        run: |
+          yarn extract-errors
+          git diff --quiet || (echo "Found unminified errors. Either update the error codes map or disable error minification for the affected build, if appropriate." && false)
+
   check_release_dependencies:
     name: Check release dependencies
     needs: build_and_lint
